name: Java CI with Maven

on:
  push:
    branches: [ 13.0.x ]
  pull_request:
    branches: [ 13.0.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn install -DskipTests=true -B -V -Psource-quality
